// app/layout.tsx
import ClientProviders from "./client-providers";
import "./globals.css";

export const metadata = {
  title: "PNR Shopping",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
